name: Update README

on:
  schedule:
    - cron: "0 */12 * * *"   
  workflow_dispatch:          

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Commit README refresh
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit --allow-empty -m "🔄 Updated GitHub stats"
          git push
